# Generated by Django 4.2.16 on 2025-01-29 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("legal_advice_builder", "0008_alter_answer_creator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="condition",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="legal_advice_builder.question",
            ),
        ),
        migrations.AlterField(
            model_name="textblockcondition",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="legal_advice_builder.question",
            ),
        ),
    ]
